name: Java Application Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      terraform-version:
        type: string
        default: '1.9.6'
      deploy-artifact:
        type: boolean
        required: true
      build-docker:
        type: boolean
        required: true
      apply-infra:
        type: boolean
        required: true
      environment:
        type: string
        required: true
      dry-run:
        type: boolean
        required: true

    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-version:
    name: Build and Extract Version
    uses: ./.github/workflows/build-and-extract-version.yml
    with:
      java-version: ${{ inputs.java-version }}

  deploy-artifact-snapshot:
    name: Deploy Snapshot to Nexus
    if: ${{ inputs.deploy-artifact && needs.build-version.outputs.is_snapshot == 'true' }}
    needs: build-version
    uses: ./.github/workflows/deploy-java-maven-snapshot.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.build-version.outputs.version }}
    secrets: inherit

  deploy-artifact-release-candidate:
    name: Deploy RC to Nexus
    if: ${{ inputs.deploy-artifact && needs.build-version.outputs.is_release_candidate == 'true' }}
    needs: build-version
    uses: ./.github/workflows/deploy-java-maven-release-candidate.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.build-version.outputs.version }}
    secrets: inherit

  deploy-artifact-release:
    name: Deploy Final Release to Nexus
    if: ${{ inputs.deploy-artifact && needs.build-version.outputs.is_release == 'true' }}
    needs: build-version
    uses: ./.github/workflows/deploy-java-maven-release.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.build-version.outputs.version }}
    secrets: inherit

  docker-build-and-push:
    name: Build & Push Docker Image
    if: ${{ inputs.build-docker }}
    needs: 
      - build-version
      - deploy-artifact-snapshot
      - deploy-artifact-release-candidate
      - deploy-artifact-release
    uses: ./.github/workflows/create-docker-image.yml
    with:
      java-version: ${{ inputs.java-version }}
    secrets: inherit

  terraform-apply-infra:
    name: Apply Terraform Infrastructure
    if: ${{ inputs.apply-infra }}
    needs: docker-build-and-push
    uses: ./.github/workflows/apply-terraform-infra.yml
    with:
      terraform_version: ${{ inputs.terraform-version }}
      base_version: ${{ needs.build-version.outputs.version }}
      deploy_infra: true
      environment: ${{ inputs.environment }}
    secrets: inherit

  library-open-snapshot-pr:
    name: Open PR for Snapshot Integration
    if: ${{ needs.library-build-and-version.outputs.is_snapshot == 'true' }}
    needs: [build-version, deploy-artifact-snapshot]
    runs-on: ubuntu-latest
    uses: ./.github/workflows/open-pr.yml
    with:
      base-branch: ${{ inputs.base-branch }}
    secrets: inherit
