name: Java Application Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      terraform-version:
        type: string
        default: '1.9.6'
      deploy-artifact:
        type: boolean
        required: true
      build-docker:
        type: boolean
        required: true
      apply-infra:
        type: boolean
        required: true
      environment:
        type: string
        required: true

    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions:
  contents: read
  packages: write

jobs:

  build:
    name: Build & Extract Version
    uses: ./.github/workflows/build-and-extract-version.yml
    with:
      java-version: ${{ inputs.java-version }}

  deploy-artifact-snapshot:
    if: ${{ needs.build.outputs.is_snapshot == 'true' }}
    needs: build
    uses: ./.github/workflows/deploy-java-maven-snapshot.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: false
    secrets: inherit

  deploy-artifact-release-candidate:
    if: ${{ needs.build.outputs.is_release_candidate == 'true' }}
    needs: build
    uses: ./.github/workflows/deploy-java-maven-release-candidate.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: false
    secrets: inherit

  deploy-artifact-release:
    if: ${{ needs.build.outputs.is_release == 'true' }}
    needs: build
    uses: ./.github/workflows/deploy-java-maven-release.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: true
    secrets: inherit

    create-docker-image:
      name: Create Docker Image
      needs: [build, deploy-artifact-snapshot, deploy-artifact-release-candidate, deploy-artifact-release]
      secrets: inherit
      uses: ./.github/workflows/create-docker-image.yml
      with:
        java-version: ${{ inputs.java-version }}

  apply-terraform:
    uses: ./.github/workflows/apply-terraform-infra.yml
    needs: [create-docker-image]
    secrets: inherit
    with:
      terraform_version: ${{ inputs.terraform-version }}
      base_version: ${{ needs.deploy-artifact.outputs.final_version }}
      deploy_infra: true
