name: Java Library Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '21'
      base-branch:
        required: false
        type: string
        default: 'develop'
      dry-run:
        type: boolean
        required: false
        default: false
    secrets:
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false

permissions:
  contents: read
  packages: write

jobs:
  library-build-and-version:
    name: Build & Extract Version
    uses: ./.github/workflows/build-and-extract-version.yml
    with:
      java-version: ${{ inputs.java-version }}

  library-deploy-snapshot:
    name: Deploy Snapshot to Nexus
    if: ${{ needs.library-build-and-version.outputs.is_snapshot == 'true' }}
    needs: library-build-and-version
    uses: ./.github/workflows/deploy-java-maven-snapshot.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.library-build-and-version.outputs.version }}
    secrets: inherit

  library-deploy-release-candidate:
    name: Deploy RC to Nexus
    if: ${{ needs.library-build-and-version.outputs.is_release_candidate == 'true' }}
    needs: library-build-and-version
    uses: ./.github/workflows/deploy-java-maven-release-candidate.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.library-build-and-version.outputs.version }}
    secrets: inherit

  library-deploy-final-release:
    name: Deploy Final Release to Nexus
    if: ${{ needs.library-build-and-version.outputs.is_release == 'true' }}
    needs: library-build-and-version
    uses: ./.github/workflows/deploy-java-maven-release.yml
    with:
      java-version: ${{ inputs.java-version }}
      dry-run: ${{ inputs.dry-run }}
      version: ${{ needs.library-build-and-version.outputs.version }}
    secrets: inherit

  library-open-snapshot-pr:
    name: Open PR for Snapshot Integration
    if: ${{ needs.library-build-and-version.outputs.is_snapshot == 'true' }}
    needs:
      - library-build-and-version
      - library-deploy-snapshot
    uses: ./.github/workflows/open-pr.yml
    with:
      base-branch: ${{ inputs.base-branch }}
    secrets: inherit
