# name: Java Application Pipeline

# on:
#   workflow_call:
#     inputs:
#       java-version:
#         type: string
#         default: '21'
#       terraform-version:
#         type: string
#         default: '1.9.6'
#       deploy-artifact:
#         type: boolean
#         default: false
#       build-docker:
#         type: boolean
#         default: false
#       apply-infra:
#         type: boolean
#         default: false
#       environment:
#         type: string
#         default: 'dev'
#     secrets:
#       NEXUS_USERNAME:
#         required: false
#       NEXUS_PASSWORD:
#         required: false
#       AWS_ACCESS_KEY_ID:
#         required: false
#       AWS_SECRET_ACCESS_KEY:
#         required: false

# permissions:
#   contents: read
#   packages: write

# jobs:

#   build:
#     name: Build & Extract Version
#     uses: ./.github/workflows/.build-and-extract-version.yml
#     with:
#       java-version: ${{ inputs.java-version }}

#   deploy-artifact:
#     if: ${{ inputs.deploy-artifact }}
#     needs: build
#     uses: ./.github/workflows/deploy-java-maven-artifact.yml
#     with:
#       java-version: ${{ inputs.java-version }}
#     secrets: inherit

#   docker-build:
#     if: ${{ inputs.build-docker }}
#     needs: [build, deploy-artifact]
#     uses: ./.github/workflows/.docker-build-only.yml
#     with:
#       java-version: ${{ inputs.java-version }}
#     secrets: inherit

#   docker-push:
#     if: ${{ inputs.build-docker }}
#     needs: docker-build
#     uses: ./.github/workflows/.docker-push.yml
#     secrets: inherit

#   terraform-plan:
#     if: ${{ inputs.apply-infra }}
#     needs: [docker-push]
#     uses: ./.github/workflows/.terraform-plan.yml
#     with:
#       terraform_version: ${{ inputs.terraform-version }}
#       environment: ${{ inputs.environment }}
#       image_tag: ${{ needs.build.outputs.version }}
#     secrets: inherit

#   terraform-apply:
#     if: ${{ inputs.apply-infra }}
#     needs: terraform-plan
#     uses: ./.github/workflows/.terraform-apply.yml
#     with:
#       terraform_version: ${{ inputs.terraform-version }}
#       environment: ${{ inputs.environment }}
#       image_tag: ${{ needs.build.outputs.version }}
#     secrets: inherit
